Build UI for e shop page
st-hieuvo2/FE-Internship-2021_Hieu-Vo-V_FE-Exercise pull request #19
Opened 2021-04-19 04:07 UTC by st-hieuvo2

Description:
- Install node-sass.
- Build structure SCSS folder.
- Apply SCSS to make UI for e shop page.

References:
- #18

2021-04-23 02:18 UTC, st-manhle requested changes
@st-hieuvo2 
check cmt

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +      <div class="container flex f-row f-center">
`f-center` theo trục gì e?
Yêu cầu dùng `flex-center-x`, `flex-center-y`

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +      <div class="container flex f-row f-center">
Sửa những chỗ tương tự

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +                <i class="search-icon">
e bọc `img` bằng thẻ `i` làm chi ri?

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +        <div class="section-image">
dùng `div` ở đây với lý do gì e?

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +              <i class="shop-now-icon">
`i > img` ?

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +                src="./resources/images/sample/collection.jpg"
lùi 1 tab cho attribute vào nhé

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +                class="item-image"
đặt tên cho đồng bộ với title nghe e
đã là item-image thì phải là item-title, còn nếu là title thì phải là image
Khuyến khích viết tắt img thay vì image

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +              <p class="title one-row">New arrivalsare now in!</p>
wrap `title, btn, sale` bằng 1 thẻ div

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +              <span class="sales-percent sale-summer-collection">-50%</span>
E đặt tên sao cho mang tính chất chung để dùng ở những chỗ khác

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +            <p class="selected-title">Selected just for you</p>
Dùng thẻ heading e nhé,
h3

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +            <a href="#" class="btn btn-custom">SHOW MORE</a>
vứt xuống dưới ul nghe e
đặt tên theo concept của bootstrap, k đặt btn-custom

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +                    src="./resources/images/sample/prd1.jpg"
tab attribute vào
```
<img
  src=""
  alt=""
>
```

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +                  <span class="sales-percent">-30%</span>
sale nằm trong prd-content chứ e

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +            <p class="section-title txt-center">Why should you choose us?</p>
h3

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +                    <img
Cái chi ri e ?
Tại sao lại có 2 hình ở đây?

2021-04-23 02:18 UTC, st-manhle commented on exercise-e-shop/index.html
> +            <p class="section-title txt-center">Products in today</p>
h3

2021-04-23 02:21 UTC, st-hieuvo2 commented on exercise-e-shop/index.html
> +                    <img
em làm hover để chuyển hình á anh. Hình đen thành hình vàng á

2021-04-23 02:40 UTC, st-hieuvo2 commented on exercise-e-shop/index.html
> +      <div class="container flex f-row f-center">
dạ ban đầu em làm f-center là cả trục x với y luôn. Để em fix lại.

2021-04-23 04:17 UTC, st-hieuvo2 commented on exercise-e-shop/index.html
> +        <div class="section-image">
dạ em làm cái overlay á anh. em dùng after để phủ 1 lớp lên cái div ni

2021-04-23 04:24 UTC, st-manhle requested changes
@st-hieuvo2

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_all.scss
> +@import 'grid.scss'
sao e import khác syntax khác những cái ở trên ri?

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_base.scss
> +    @include text-format($regular, $font-size-xl, #cecece !important);
sắp xếp mixin lên trên cùng nghe e

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_base.scss
> +      content: "$89.99";
dùng attr(data-attr)

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_base.scss
> +.prd-discount {
cái này k phải ở base, ở module nghe e

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_base.scss
> +.advantage-horizontal {
module not base

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_base.scss
> +  @include txt-ellipsis(2, 1.5em);
đưa mixin len trên

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_base.scss
> +}
add end line

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_fonts.scss
> +$page-font-family: 'Poppins', san-serif;
đưa những biến này qua file variables e nhes

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_grid.scss
> +@include create-columns-sm(8px, 8px, 576px);
add end line

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_mixins.scss
> +@mixin top-left-absolute($top, $left) {
k qúa lạm dụng mixin nghe e, kiểm tra lại những cái khác

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_mixins.scss
> +@mixin flex-end {
cái này là extend chứ sao mxin e nhỉ

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_variables.scss
> +/*Color*/
tạo variable theo dạng
```
$color: (
  primary: #fff,
  secondry: #000
)
```

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/components/_product-list.scss
> +      .prd-image {
`&-image`

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/components/_product-list.scss
> +      .prd-title {
`&-title`

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/components/_product-list.scss
> +      .prd-price {
`&-price`

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/layout/_footer.scss
> +    .left-footer-content {
`&-content`

2021-04-23 04:24 UTC, st-manhle commented on exercise-e-shop/resources/scss/layout/_footer.scss
> +      @include text-format(
bớt lạm dụng mixin nghe e

2021-04-23 04:29 UTC, st-hieuvo2 commented on exercise-e-shop/index.html
> +              <span class="sales-percent sale-summer-collection">-50%</span>
dạ cái này em bị thừa cái sale-summer-collection

2021-04-23 07:06 UTC, st-manhle requested changes
@st-hieuvo2 
Check lại HTML

2021-04-23 07:06 UTC, st-manhle commented on exercise-e-shop/index.html
> +                <p class="title one-row">New arrivalsare now in!</p>
title chỗ này dùng h3 nghe e

2021-04-23 07:06 UTC, st-manhle commented on exercise-e-shop/index.html
> +                      <p class="prd-title">T-Shirt Summer Vibes</p>
dùng heading cho title prd

2021-04-23 07:06 UTC, st-manhle commented on exercise-e-shop/index.html
> +                      <p class="prd-title">T-Shirt Summer Vibes</p>
dùng heading

2021-04-23 07:49 UTC, st-manhle requested changes
@st-hieuvo2

2021-04-23 07:49 UTC, st-manhle commented on exercise-e-shop/index.html
> +      <div class="container f-row f-center-x f-center-y-sm">
`f-center-y-sm`
Style trong css nghe e, dùng class ri k hay

2021-04-23 07:58 UTC, st-hieuvo2 commented on exercise-e-shop/index.html
> +      <div class="container f-row f-center-x f-center-y-sm">
dạ ok anh

2021-04-26 01:48 UTC, st-manhle requested changes

2021-04-26 01:48 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_reset.scss
> +* {
Chỉnh lại tab 2 giúp a

2021-04-26 01:48 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_variables.scss
> +/*base html font-size*/
Sửa luôn những phần khác theo convention giống color luôn chứ H?

2021-04-26 01:48 UTC, st-manhle commented on exercise-e-shop/resources/scss/base/_mixins.scss
> +.flex-end {
file mixin sao có cái này

2021-04-26 01:48 UTC, st-manhle commented on exercise-e-shop/resources/scss/modules/_advantage-horizontal.scss
> +.advantage-horizontal {
E tạo 1 file `_advantage.scss` trong component
Rồi bỏ style advantage-horizontal/vertical vào file đó luôn nghe
```
.advantage {
  &-horizontal {}
  &-vertical {}
}
```

2021-04-26 01:48 UTC, st-manhle commented on exercise-e-shop/resources/scss/modules/_sales.scss
> +.sales-percent {
cái tên file chưa tường minh lắm, e đổi cho a nghe

2021-04-26 01:48 UTC, st-manhle commented on exercise-e-shop/resources/scss/components/_product-list.scss
> +    .prd {
e add style prd-discount vào đây luôn đi

2021-04-29 08:46 UTC, merged