Exercise/20210502 hieu vo v cart layout
st-hieuvo2/FE-Internship-2021_Hieu-Vo-V_FE-Exercise pull request #28
Opened 2021-05-03 08:49 UTC by st-hieuvo2

Description:
- Build cart layout, use default data to render products.
- Apply SCSS to build UI.
- Update quantity on the cart.

References:
- #26 

Images:
![Cart_layout](https://user-images.githubusercontent.com/82006669/116857411-f68b6f80-ac26-11eb-98a8-c488c55aa071.png)

2021-05-05 06:45 UTC, st-manhle requested changes
check cmt

2021-05-05 06:45 UTC, st-manhle commented on exercise-e-shop/resources/scss/components/_cart-product-list.scss
> +	@include to-rem(padding, 16, 16, 16, 16);
sao có mixin `to-rem` rồi còn `calculateRem` nữa e

2021-05-05 06:45 UTC, st-manhle commented on exercise-e-shop/resources/scss/components/_cart-product-list.scss
> +			height: 200px;
sao vẫn còn `px` e, sửa hết mấy chỗ khác luôn nghe

2021-05-05 06:45 UTC, st-manhle commented on exercise-e-shop/resources/scss/layout/_header.scss
> +    background-color: #ffffff;
mã màu bỏ vào variable nghe e

2021-05-05 06:52 UTC, st-hieuvo2 commented on exercise-e-shop/resources/scss/components/_cart-product-list.scss
> +	@include to-rem(padding, 16, 16, 16, 16);
dạ cái to-rem là dành cho bộ margin với padding anh, còn calculate Rem là convert các px đơn lẻ sang rem anh

2021-05-10 02:14 UTC, st-manhle commented on exercise-e-shop/resources/scss/components/_cart-product-list.scss
> +	@include pxRem(padding, 16);
để ý tab e ơi

2021-05-10 04:51 UTC, st-manhle commented on exercise-e-shop/resources/scss/modules/_buttons.scss
> +  background-color: map-get($color, "primary");
@st-hieuvo2 
Sao chỗ này có 2 background á e

2021-05-10 04:53 UTC, st-hieuvo2 commented on exercise-e-shop/resources/scss/modules/_buttons.scss
> +  background-color: map-get($color, "primary");
ui sorry anh, cái này em accept both mà quên xóa .

2021-05-10 05:05 UTC, merged